// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class AdministrarDetallesPedidoTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void administrarDetallesPedido() {
    driver.Navigate().GoToUrl("http://localhost:44411/");
    driver.Manage().Window.Size = new System.Drawing.Size(761, 718);
    driver.FindElement(By.Name("email")).SendKeys("maria@example.com");
    driver.FindElement(By.Name("password")).SendKeys("mb90");
    driver.FindElement(By.CssSelector(".login-submit")).Click();
    driver.FindElement(By.CssSelector(".nav-item:nth-child(4) span")).Click();
    driver.FindElement(By.LinkText("Administrar Pedidos")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(1) .btn-secondary")).Click();
    driver.FindElement(By.CssSelector(".btn-danger")).Click();
    driver.FindElement(By.CssSelector(".swal2-confirm")).Click();
    driver.FindElement(By.CssSelector(".nav-item:nth-child(5) .fas")).Click();
    driver.FindElement(By.LinkText("Ver carrito")).Click();
    driver.FindElement(By.LinkText("Administrar Pedidos")).Click();
    driver.FindElement(By.CssSelector(".nav-item:nth-child(5) .fas")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(1) .btn-danger")).Click();
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(1) .btn-danger"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.TagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".swal2-confirm")).Click();
  }
}
