// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class EliminarInventarioTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void eliminarInventario() {
    driver.Navigate().GoToUrl("http://localhost:44411/");
    driver.Manage().Window.Size = new System.Drawing.Size(1050, 700);
    driver.FindElement(By.Name("email")).SendKeys("juan@example.com");
    driver.FindElement(By.Name("password")).SendKeys("jk123");
    driver.FindElement(By.CssSelector(".login-submit")).Click();
    driver.FindElement(By.CssSelector(".nav-item:nth-child(4) span")).Click();
    driver.FindElement(By.LinkText("Administrar Inventario")).Click();
    driver.FindElement(By.CssSelector(".table-warning:nth-child(1) .btn-danger")).Click();
    driver.FindElement(By.CssSelector(".swal2-confirm")).Click();
    driver.FindElement(By.CssSelector(".btn-success")).Click();
    driver.FindElement(By.Name("descripcion")).Click();
    driver.FindElement(By.Name("descripcion")).SendKeys("Lote #3 de esponjas mezcladoras de maquillaje");
    driver.FindElement(By.Name("cantidad")).Click();
    driver.FindElement(By.Name("cantidad")).SendKeys("62");
    driver.FindElement(By.Name("fechaRegistro")).Click();
    driver.FindElement(By.CssSelector(".react-datepicker__day--keyboard-selected")).Click();
    driver.FindElement(By.Name("fechaCaduca")).Click();
    driver.FindElement(By.CssSelector(".react-datepicker__navigation-icon--next")).Click();
    driver.FindElement(By.CssSelector(".react-datepicker__navigation-icon--next")).Click();
    driver.FindElement(By.CssSelector(".react-datepicker__navigation-icon--next")).Click();
    driver.FindElement(By.CssSelector(".react-datepicker__navigation--next")).Click();
    driver.FindElement(By.CssSelector(".react-datepicker__navigation--next")).Click();
    driver.FindElement(By.CssSelector(".react-datepicker__day--005")).Click();
    driver.FindElement(By.Name("estado")).Click();
    {
      var dropdown = driver.FindElement(By.Name("estado"));
      dropdown.FindElement(By.XPath("//option[. = 'En existencia']")).Click();
    }
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
  }
}
