// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TodasLasVistasClienteAdminTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void todasLasVistasClienteAdmin() {
    driver.Navigate().GoToUrl("http://localhost:44411");
    driver.Manage().Window.Size = new System.Drawing.Size(1050, 700);
    driver.FindElement(By.Name("email")).SendKeys("maria@example.com");
    driver.FindElement(By.Name("password")).SendKeys("mb90");
    driver.FindElement(By.CssSelector(".login-submit")).Click();
    driver.FindElement(By.CssSelector(".nav-item:nth-child(5) span")).Click();
    driver.FindElement(By.LinkText("Ver carrito")).Click();
    driver.FindElement(By.CssSelector(".nav-item:nth-child(5) span")).Click();
    driver.FindElement(By.LinkText("Pedidos")).Click();
    driver.FindElement(By.LinkText("Administrar Pedidos")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(1) .btn-secondary")).Click();
    driver.FindElement(By.CssSelector(".nav-item:nth-child(4) span")).Click();
    driver.FindElement(By.CssSelector(".nav-item:nth-child(3) span")).Click();
    driver.FindElement(By.LinkText("Administrar Inventario")).Click();
    driver.Navigate().GoToUrl("http://localhost:44411");
    driver.FindElement(By.Name("email")).SendKeys("juan@example.com");
    driver.FindElement(By.Name("password")).SendKeys("jk123");
    driver.FindElement(By.Name("password")).Click();
    driver.FindElement(By.CssSelector(".login-submit")).Click();
    driver.FindElement(By.CssSelector(".nav-item:nth-child(4) span")).Click();
    driver.FindElement(By.LinkText("Administrar Inventario")).Click();
    driver.FindElement(By.LinkText("Inventario")).Click();
    driver.FindElement(By.CssSelector(".nav-item:nth-child(7) span")).Click();
    driver.FindElement(By.LinkText("Administrar Pedidos")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(2) .btn-secondary")).Click();
    driver.FindElement(By.LinkText("Administrar Pedidos")).Click();
    driver.FindElement(By.CssSelector(".nav-item:nth-child(7) span")).Click();
    driver.FindElement(By.CssSelector(".nav-item:nth-child(6) span")).Click();
    driver.FindElement(By.LinkText("Administrar Clientes")).Click();
    driver.FindElement(By.CssSelector(".nav-item:nth-child(6) span")).Click();
    driver.FindElement(By.CssSelector(".nav-item:nth-child(7) span")).Click();
    driver.FindElement(By.LinkText("Administrar Pedidos")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(2) .btn-danger")).Click();
    driver.FindElement(By.CssSelector(".swal2-confirm")).Click();
    driver.FindElement(By.CssSelector(".nav-item:nth-child(4) span")).Click();
    driver.FindElement(By.LinkText("Administrar Inventario")).Click();
    driver.FindElement(By.LinkText("Administrar Pedidos")).Click();
  }
}
